- hosts: all
  user: root
  vars_files:
    - ../external_vars.yaml

  tasks:
  - name: copia systemd-udevd
    copy:
      src: "{{source_files}}/source/je-script/scripts/systemd-udevd.service.d"
      dest: /etc/systemd/system/systemd-udevd.service.d
      owner: root
      group: root
      mode: 0644
    register: copia_systemd_udevd

  - name: restart udev
    command: udevadm control --reload
    when: copia_systemd_udevd.changed

  - name: copia scripts do sistema
    copy:
      src:  "{{source_files}}/source/je-script/scripts/{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: "{{ item.mode }}"
    with_items:
      - { src: 'integridade/sbin/je-connect-chksum', dest: '/sbin', mode: '0750' }
      - { src: 'integridade/sbin/je-connect-brick', dest: '/sbin', mode: '0750' }
      - { src: 'je-connect-boot', dest: '/sbin', mode: '0750' }
      - { src: 'integridade/systemd/je-connect-chksum.service', dest: '/lib/systemd/system', mode: '0644' }
      - { src: 'integridade/systemd/je-connect-env.service', dest: '/lib/systemd/system', mode: '0644' }
      - { src: 'je-connect-boot.service', dest: '/lib/systemd/system', mode: '0644' }
      - { src: 'initrd/chkmem', dest: '/usr/share/initramfs-tools/scripts/init-top', mode: '0000' }
      - { src: 'scrypt-kdf/scrypt-master/bin64/scrypt-kdf', dest: '/bin', mode: '0750' }
      - { src: 'scrypt-kdf/scrypt-master/bin64/libscrypt.so', dest: '/lib', mode: '0644' }
      - { src: 'askpass/askpass-je-2022', dest: '/lib/cryptsetup/askpass-je', mode: '0755' }

  - name: copia arquivos do initramfs-tools
    copy:
      remote_src: yes
      src: "/usr/share/initramfs-tools/{{item}}"
      dest: "/etc/initramfs-tools/{{item}}"
      mode: preserve
    with_items:
      - hooks/cryptroot
      - scripts/local-top/cryptroot

  - name: aplica patch em /etc/systemd/resolved.conf
    patch:
      src: "{{source_files}}/source/je-script/patches/resolved-conf.patch"
      dest: /etc/systemd/resolved.conf
  
  - name: aplica patch em /etc/initramfs-tools/hooks/cryptroot
    patch:
      src: "{{source_files}}/source/je-script/patches/hooks_cryptroot.patch"
      dest: /etc/initramfs-tools/hooks/cryptroot

  - name: aplica patch em /etc/initramfs-tools/scripts/local-top/cryptroot
    patch:
      src: "{{source_files}}/source/je-script/patches/scripts_localtop_cryptroot.patch"
      dest: /etc/initramfs-tools/scripts/local-top/cryptroot

  - name: aplica patch em /usr/lib/cryptsetup/functions
    patch:
      src: "{{source_files}}/source/je-script/patches/cryptroot_functions.patch"
      dest: /usr/lib/cryptsetup/functions

  - name: recria o initram
    shell: update-initramfs -u

